Update cypress-test-docker-image.yml

diff --git a/.github/workflows/cypress-test-docker-image.yml b/.github/workflows/cypress-test-docker-image.yml
--- a/.github/workflows/cypress-test-docker-image.yml
+++ b/.github/workflows/cypress-test-docker-image.yml
@@ -59,18 +59,18 @@ jobs:
             u6687032/hello-devops-backend:latest
 
       # ✅ ตรวจสอบ backend
-      - name: Check backend health
-        run: |
-          for i in {1..15}; do
-            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
-              echo "✅ Backend OK"
-              exit 0
-            fi
-            echo "⏳ Retry ($i/15)..."
-            sleep 5
-          done
-          docker logs backend
-          exit 1
+      # - name: Check backend health
+      #   run: |
+      #     for i in {1..15}; do
+      #       if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
+      #         echo "✅ Backend OK"
+      #         exit 0
+      #       fi
+      #       echo "⏳ Retry ($i/15)..."
+      #       sleep 5
+      #     done
+      #     docker logs backend
+      #     exit 1
           
       - name: Run backend container from Docker Hub
         run: |
