Update cypress-test-docker-image.yml

diff --git a/.github/workflows/cypress-test-docker-image.yml b/.github/workflows/cypress-test-docker-image.yml
--- a/.github/workflows/cypress-test-docker-image.yml
+++ b/.github/workflows/cypress-test-docker-image.yml
@@ -72,26 +72,26 @@ jobs:
       #     docker logs backend
       #     exit 1
           
-      - name: Run backend container from Docker Hub
-        run: |
-          docker network create testnet
-          docker network connect testnet $(docker ps -qf "name=mysql")
-          docker run -d --network testnet -p 8080:8080 --name backend u6687032/hellodevops-backend:latest
+      # - name: Run backend container from Docker Hub
+      #   run: |
+      #     docker network create testnet
+      #     docker network connect testnet $(docker ps -qf "name=mysql")
+      #     docker run -d --network testnet -p 8080:8080 --name backend u6687032/hellodevops-backend:latest
       
-      - name: Check backend health
-        run: |
-          echo "⏳ Waiting for backend..."
-          for i in {1..20}; do
-            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
-              echo "✅ Backend is up!"
-              exit 0
-            fi
-            echo "❌ Retry ($i/20)..."
-            sleep 6
-          done
-          echo "❌ Backend did not respond in time."
-          docker logs backend || true
-          exit 1
+      # - name: Check backend health
+      #   run: |
+      #     echo "⏳ Waiting for backend..."
+      #     for i in {1..20}; do
+      #       if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
+      #         echo "✅ Backend is up!"
+      #         exit 0
+      #       fi
+      #       echo "❌ Retry ($i/20)..."
+      #       sleep 6
+      #     done
+      #     echo "❌ Backend did not respond in time."
+      #     docker logs backend || true
+      #     exit 1
 
 
 
